language: python
python:
    - 3.5
    - 3.4
    - 3.3

install:
    - pip install -r dev_requirements.txt
    - pip install coveralls
script:
    - make lint
    - make test
after_success:
    coveralls
